package com.survey.project.application.utils.constants

object FragmentTagConstants {

    const val sixtenFragmentTag = "SixteenFragment"
    const val seventeenFragmentTag = "SeventeenFragment"
    const val eighteenFragmentTag = "EighteenFragment"
    const val nineteenFragmentTag = "nineteenFragmentTag"
    const val twentyFragmentTag = "twentyFragmentTag"
    const val twentyOneFragmentTag = "twentyOneFragmentTag"
    const val twentyTwoFragmentTag = "twentyTwoFragmentTag"
    const val twentyThreeFragmentTag = "twentyThreeFragmentTag"
    const val twentyFourFragmentTag = "twentyFourFragmentTag"
    const val twentyFiveFragmentTag = "twentyFiveFragmentTag"
    const val twentySixFragmentTag = "twentySixFragmentTag"
    const val twentySevenFragmentTag = "twentySevenFragmentTag"
    const val twentyEightFragmentTag = "twentyEightFragmentTag"
    const val twentyNineFragmentTag = "twentyNineFragmentTag"
    const val thirtyFragmentTag = "thirtyFragmentTag"

    const val nameFragmentTag = "NameFragment"
    const val mainPage = "MainPage"
    const val homeFragmentTag = "HomeFragment"
    const val signUpFragmentTag = "SignUpFragment"
    const val forgotPasswordFragmentTag = "ForgotPasswordFragment"
    const val question1Fragment = "question1Fragment"
    const val question2Fragment = "question2Fragment"
    const val question3Fragment = "question3Fragment"
    const val question4Fragment = "question4Fragment"
    const val question5Fragment = "question5Fragment"
    const val question6Fragment = "question6Fragment"
    const val question7Fragment = "question7Fragment"
    const val question8Fragment = "question8Fragment"
    const val question9Fragment = "question9Fragment"
    const val question10Fragment = "question10Fragment"
    const val question11Fragment = "question11Fragment"
    const val question12Fragment = "question12Fragment"
    const val question13Fragment = "question13Fragment"
    const val question14Fragment = "question14Fragment"
    const val question15Fragment = "question15Fragment"
    const val resetFragmentTag = "ResetFragment"
}
