package com.survey.project.application.utils.constants

object FragmentTagConstants {

    const val sixtenFragmentTag = "SixteenFragment"
    const val seventeenFragmentTag = "SeventeenFragment"
    const val eighteenFragmentTag = "EighteenFragment"
    const val nineteenFragmentTag = "nineteenFragmentTag"
    const val twentyFragmentTag = "twentyFragmentTag"
    const val twentyOneFragmentTag = "twentyOneFragmentTag"
    const val twentyTwoFragmentTag = "twentyTwoFragmentTag"
    const val twentyThreeFragmentTag = "twentyThreeFragmentTag"
    const val twentyFourFragmentTag = "twentyFourFragmentTag"
    const val twentyFiveFragmentTag = "twentyFiveFragmentTag"
    const val twentySixFragmentTag = "twentySixFragmentTag"
    const val twentySevenFragmentTag = "twentySevenFragmentTag"
    const val twentyEightFragmentTag = "twentyEightFragmentTag"
    const val twentyNineFragmentTag = "twentyNineFragmentTag"
    const val thirtyFragmentTag = "thirtyFragmentTag"

    const val nameFragmentTag = "NameFragment"
    const val mainPage = "MainPage"
    const val homeFragmentTag = "HomeFragment"
    const val signUpFragmentTag = "SignUpFragment"
    const val forgotPasswordFragmentTag = "ForgotPasswordFragment"
    const val question1Fragment = "question1Fragment"
    const val question2Fragment = "question2Fragment"
    const val question3Fragment = "question3Fragment"
    const val question4Fragment = "question4Fragment"
    const val question5Fragment = "question5Fragment"
    const val question6Fragment = "question6Fragment"
    const val question7Fragment = "question7Fragment"
    const val question8Fragment = "question8Fragment"
    const val question9Fragment = "question9Fragment"
    const val question10Fragment = "question10Fragment"
    const val question11Fragment = "question11Fragment"
    const val question12Fragment = "question12Fragment"
    const val question13Fragment = "question13Fragment"
    const val question14Fragment = "question14Fragment"
    const val question15Fragment = "question15Fragment"
    const val resetFragmentTag = "ResetFragment"

    //    Section3
    const val question1Sec3 = "question1Sec3"
    const val question2Sec3 = "question2Sec3"
    const val question3Sec3 = "question3Sec3"
    const val question4Sec3 = "question4Sec3"
    const val question5Sec3 = "question5Sec3"
    const val question6Sec3 = "question6Sec3"
    const val question7Sec3 = "question7Sec3"
    const val question8Sec3 = "question8Sec3"
    const val question9Sec3 = "question9Sec3"
    const val question10Sec3 = "question10Sec3"
    const val question11Sec3 = "question11Sec3"

    //section2
    const val questionB1 = "questionB1"
    const val questionB2 = "questionB2"
    const val questionB3 = "questionB3"
    const val questionB4 = "questionB4"
    const val questionB5 = "questionB5"
    const val questionB6 = "questionB6"
    const val questionB7 = "questionB7"
    const val questionB8 = "questionB8"
    const val questionB9 = "questionB9"
    const val questionB10 = "questionB10"
    const val questionB11 = "questionB11"
    const val questionB12 = "questionB12"
    const val questionB13 = "questionB13"
    const val sectionBResults = "sectionBResults"
}
