package com.survey.project.application.utils.constants

object PreferenceConstants {
    const val main_preference = "Section1"

    const val ethnicity = "ethnicity"
    const val religion = "religion"
    const val language = "language"
    const val house_type = "house_type"
    const val house_ownership = "house_ownership"
    const val house_rented = "house_rented"
    const val rented_land = "rented_land"
    const val rented_area_numbers = "rented_area_numbers"
    const val monthly_income = "monthly_income"
    const val bank_account_present = "bank_account_present"
    const val monthly_saving = "monthly_saving"
    const val unemployment_in_family = "unemployment_in_family"
    const val male_unemployed = "male_unemployed"
    const val female_unemployed = "female_unemployed"
    const val third_gender_unemployed = "third_gender_unemployed"
    const val businessType = "businessType"
    const val lalpurja = "lalpurja"
    const val count = "count"
    const val businessCount = "businessCount"

    const val section_b_preference = "Section2"
    const val dead_count_male = "dead_count_male"
    const val dead_count_female = "dead_count_female"
    const val dead_count_third = "dead_count_third"
    const val sent_kids_to_school = "sent_kids_to_school"
    const val schoolType = "schoolType"
    const val childLabor = "childLabor"
    const val sonCountInCountry = "sonCountInCountry"
    const val daughterCountInCountry = "daughterCountInCountry"
    const val sonCountInForeign = "sonCountInForeign"
    const val daughterCountInForeign = "daughterCountInForeign"
    const val ghareluKamdarSon = "ghareluKamdarSon"
    const val ghareluKamdarDaughter = "ghareluKamdarDaughter"
    const val karkhanaDaughter = "karkhanaDaughter"
    const val karkhanaSon = "karkhanaSon"
    const val byaparSon = "byaparSon"
    const val byaparDaughter = "byaparDaughter"
    const val krishiDaughter = "krishiDaughter"
    const val krishiSon = "krishiSon"
    const val karyalayaSon = "karyalayaSon"
    const val karyalayaDaughter = "karyalayaDaughter"
    const val circusDaughter = "circusDaughter"
    const val circusSon = "circusSon"
    const val gotYourKidMarriedBefore18 = "gotYourKidMarriedBefore18"
    const val sonDaughterMarriedBefore18 = "sonDaughterMarriedBefore18"
    const val differentlyAbledInFam = "differentlyAbledInFam"
    const val differentlyAbledType = "differentlyAbledType"
    const val cardType = "cardType"
    const val longTermDisease = "longTermDisease"
    const val tbCount = "tbCount"
    const val cancerCount = "cancerCount"
    const val hivCount = "hivCount"
    const val sugarCount = "sugarCount"
    const val bpCount = "bpCount"
}